version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.7
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ELASTIC_PASSWORD: admin
      discovery.type: single-node

  zipkin:
    container_name: zipkin
    hostname: 127.0.0.1
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    environment:
      STORAGE_TYPE: elasticsearch
      ES_HOSTS: elasticsearch:9200
      ES_PASSWORD: admin
      RABBIT_QUEUE: zipkin
      RABBIT_ADDRESSES: rabbitmq:5672
      RABBIT_PASSWORD: admin
      RABBIT_USER: admin
    depends_on:
      elasticsearch:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 10

  keycloak_db:
    container_name: keycloak_db
    hostname: 127.0.0.1
    image: postgres
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: microservices_template_keycloak_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_db
      DB_DATABASE: microservices_template_keycloak_db
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: root
    ports:
      - "18080:18080"
    command:
      - "-b"
      - "0.0.0.0"
      - "-Djboss.socket.binding.port-offset=10000"
    restart: on-failure
    depends_on:
      keycloak_db:
        condition: service_started