CREATE TYPE metadata_property_name AS ENUM (
'name',
'version',
'uuid',
'collation',
'default_schema',
'is_system',
'extension_owner_id',
'extension_namespace_id',
'extension_is_relocatable',
'extension_version',
'is_typed_table',
'is_updatable',
'text',
'has_indexes',
'is_aggregate',
'is_trigger_function',
'return_type');