CREATE TYPE metadata_category_type AS ENUM(
    'Servers',
    'Databases',
    'Schemas',
    'Extensions',
    'Tables',
    'Views',
    'Materialized views',
    'Procedures',
    'Functions',
    'Aggregate functions',
    'Sequences',
    'User defined types',
    'Partitions',
    'Columns',
    'Indexes',
    'Triggers',
    'Parameters',
    'Primary keys',
    'Foreign keys',
    'Unique keys',
    'Check constraints'
);