spring:
  application:
    name: config-server
  profiles:
    active: ${APP_PROFILE}
  cloud:
    config:
      server:
        git:
          default-label: ${CONFIG_SERVER_GIT_URI_BRANCH}
          uri: ${CONFIG_SERVER_GIT_URI}
          username: ${CONFIG_SERVER_GIT_URI_USERNAME}
          password: ${CONFIG_SERVER_GIT_URI_PASSWORD}

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 20
    serviceUrl:
      defaultZone: http://${APP_HOST}:${DISCOVERY_SERVER_PORT}/${APP_CONTEXT_PATH}/eureka/

server:
  port: ${CONFIG_SERVER_PORT}
  servlet:
    context-path: /${APP_CONTEXT_PATH}